// Re-sign old content with a fresh timestamp so clients actually select it.
import { readFile, writeFile, mkdir, rename } from 'node:fs/promises';
import { resolve } from 'node:path';
import { randomUUID, sign, verify } from 'node:crypto';
const [releaseId, channel = 'preview'] = process.argv.slice(2);
if (!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(releaseId ?? '') || !/^[a-zA-Z0-9._-]{1,128}$/.test(channel)) throw new Error('Invalid rollback target');
if (!process.env.OTA_STORAGE || !process.env.OTA_PRIVATE_KEY || !process.env.OTA_CERTIFICATE) throw new Error('Missing trusted publisher configuration');
const root = resolve(process.env.OTA_STORAGE);
const source = resolve(root, 'releases', releaseId);
const old = await readFile(resolve(source, 'manifest.json'));
const certificate = await readFile(process.env.OTA_CERTIFICATE);
const signature = await readFile(resolve(source, 'signature.txt'), 'utf8');
if (!verify('RSA-SHA256', old, certificate, Buffer.from(signature, 'base64'))) throw new Error('Archived release signature is invalid');
const manifest = JSON.parse(old);
if (!/^[a-zA-Z0-9._-]{1,128}$/.test(manifest.runtimeVersion) || !['android', 'ios'].includes(manifest.metadata.platform)) throw new Error('Invalid archived runtime');
manifest.id = randomUUID();
manifest.createdAt = new Date().toISOString();
manifest.metadata.channel = channel;
const body = JSON.stringify(manifest);
const privateKey = await readFile(process.env.OTA_PRIVATE_KEY);
const release = resolve(root, 'releases', manifest.id);
await mkdir(release, { recursive: true });
await writeFile(resolve(release, 'manifest.json'), body, { flag: 'wx' });
await writeFile(resolve(release, 'signature.txt'), sign('RSA-SHA256', Buffer.from(body), privateKey).toString('base64'), { flag: 'wx' });
const directory = resolve(root, 'channels', channel, manifest.metadata.platform);
await mkdir(directory, { recursive: true });
const temporary = resolve(directory, `${manifest.runtimeVersion}.${randomUUID()}.tmp`);
await writeFile(temporary, JSON.stringify({ id: manifest.id }));
await rename(temporary, resolve(directory, `${manifest.runtimeVersion}.json`));
console.log('Previous signed content published as a new rollback update.');
